### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by Stuperfied** [Kealper/Batchcraft#1]
Downloaded the linux version, placed in directory with server.
performed chmod +x batchcraft
added permissions 0777
changed user and group to a lesser one

The following is what I did but of course im using all fake values here.
batchcraft -a 10.0.0.10:29515 -p mypass -c "time set day"
sh: 1: batchcraft: not found

sudo batchcraft -a 10.0.0.10:29515 -p mypass -c "time set day"
sudo: batchcraft: command not found

**Comment by Kealper** [comment]
The pre-compiled Linux binary in the bin directory of the repo is 64-bit, is that system you're running it on 32-bit or 64-bit?

If you're unsure, paste the output of this command: uname -mpi

**Comment by Kealper** [comment]
I've just added both 32-bit and 64-bit builds for those who are running 32-bit Linux installations.

Give the "x86" Linux build a try from here: https://github.com/Kealper/Batchcraft/tree/master/bin/linux/x86

**Comment by Stuperfied** [comment]
Thanks but I already wrote my own bash client.
Here is my output all the same.
x86_64 x86_64 x86_64

**Comment by Stuperfied** [comment]
Oh and the hardware is a HP DL360 G6 running Ubuntu server 4.4.0-87-generic

**Comment by Kealper** [comment]
Alright so it doesn't look like that was the problem.

Out of curiosity, were you trying to run it as `./batchcraft` or just `batchcraft` in the directory it was placed in? If you were just running it directly from the server's directory, for security reasons, the current working directory typically isn't included in the places that will be searched for programs when you type a program name without saying explicitly where it is on the disk. When running a program from the current directory on Linux, you'll usually need to either use its full path or prefix it with `./` to say "check the current directory I'm in for this program".

**Comment by Stuperfied** [comment]
That was it, i've been working with batch files so much lately that I neglected to add the ./ though I am also glad this happened as I gained a lot of experience in sockets whilst writing my own version.

Thanks for the help.

**Comment by Kealper** [comment]
Glad the problem was a simple fix, I was really wracking my head trying to figure out how that wasn't able to run it until I went back and looked closely at the original issue you opened! Completely overlooked it myself at first as well.
