### ISSUE TITLE
RPi Support?

### ISSUE THREAD

**Issue by marewey** [Kealper/Batchcraft#2]
When I download either x86 or x64 files I get this error on my rpi:
-bash: ./batchcraft: cannot execute binary file: Exec format error
I would love to use this project for making an auto whitelist using php to do it.

**Comment by Kealper** [comment]
Hey there! The RPi uses an ARM-based CPU, instead of an x86-based one. Though it would be possible to compile this from source to many different CPU architectures, ARM is gaining popularity so I'll get a pre-compiled binary up that will run on RPis momentarily.

**Comment by Kealper** [comment]
The file located in `bin/linux/arm` should run on your RPi. That should save you the hassle of having to compile it from source!

**Comment by marewey** [comment]
Thanks!
